allOf:
  - title: trainset response
  - $ref: "base/response.yml"
  - properties:
      trainset:
        oneOf:
          - $ref: "../models/trainset.yml#/freight_trainset"
          - $ref: "../models/trainset.yml#/passenger_trainset"
          - $ref: "../models/trainset.yml#/work_trainset"
        discriminator:
          propertyName: object_type