title: train model
description: |
  Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
  
  Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
  
  It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. 
required:
  - train_id
  - name
  - registration_date
properties:
  train_id:
    type: integer
    minimum: 0
    description: A unique id identifing the train.
    example: 4051
  type:
    required:
      - type_id
      - name
    properties:
      type_id:
        type: string
        format: uuid
        description:  A unique id identifing the train type.
        example: f3bb9b86-698e-46ad-9b0f-95a6b906dd57
      name:
        type: string
        description: The name of the train type.
        example: ICM-2
  registration_date:
    type: string
    format: date
    description: The registration date of the train.
    example: "1981-01-05"
  



